"""empty message

Revision ID: 40a25698eeff
Revises: c77726d4545b
Create Date: 2023-04-16 12:21:34.587071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40a25698eeff'
down_revision = 'c77726d4545b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('egitmenler',
    sa.Column('egitmen_id', sa.Integer(), nullable=False),
    sa.Column('egitmen_adi', sa.String(), nullable=True),
    sa.Column('egitmen_soyadi', sa.String(), nullable=True),
    sa.Column('egitmen_alani', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('egitmen_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('egitmenler')
    # ### end Alembic commands ###
