"""empty message

Revision ID: 5ea531be34ea
Revises: 40a25698eeff
Create Date: 2023-04-16 12:22:27.240266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ea531be34ea'
down_revision = '40a25698eeff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dersler',
    sa.Column('ders_id', sa.Integer(), nullable=False),
    sa.Column('ders_adi', sa.String(), nullable=True),
    sa.Column('ders_saati', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('ders_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dersler')
    # ### end Alembic commands ###
