"""empty message

Revision ID: c77726d4545b
Revises: e7a9dee23560
Create Date: 2023-04-14 11:43:33.375050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c77726d4545b'
down_revision = 'e7a9dee23560'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('siniflar',
    sa.Column('sinif_id', sa.Integer(), nullable=False),
    sa.Column('sinif_adi', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('sinif_id')
    )
    op.create_table('dersler',
    sa.Column('ders_id', sa.Integer(), nullable=False),
    sa.Column('ders_adi', sa.String(), nullable=True),
    sa.Column('ders_ogretmen_id', sa.Integer(), nullable=True),
    sa.Column('ders_sinif_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ders_ogretmen_id'], ['ogretmenler.ogretmen_id'], ),
    sa.ForeignKeyConstraint(['ders_sinif_id'], ['siniflar.sinif_id'], ),
    sa.PrimaryKeyConstraint('ders_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dersler')
    op.drop_table('siniflar')
    # ### end Alembic commands ###
