"""empty message

Revision ID: e7a9dee23560
Revises: 
Create Date: 2023-04-14 11:33:00.769476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7a9dee23560'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ogretmenler',
    sa.Column('ogretmen_id', sa.Integer(), nullable=False),
    sa.Column('ogretmen_adi', sa.String(), nullable=True),
    sa.Column('ogretmen_soyadi', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('ogretmen_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ogretmenler')
    # ### end Alembic commands ###
